go_import_path: github.com/helloyi/go-value

language: go

env:
  global:
    - GO111MODULE="on"
    - GOFLAGS="-mod=readonly"
go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt
  - $GOPATH/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
